### ISSUE TITLE
The examples show black material/color on mobile

### ISSUE THREAD

**Issue by commentatorboy** [adrixp/aframe-charts-component#2] opened 2019-03-30 18:27 UTC
Hey. Just wanted to report that the examples show almost all black.
I suspect it has something to do with how the rendering is done, or how the objects are made.
Because when I use aframe only to create a box and use `<a-scene renderer="precision: mediump">` it works.

![55744424_316186979069916_5923181606842925056_n](https://user-images.githubusercontent.com/1793964/55280096-156cf880-5321-11e9-92c8-34030ca20632.png)

**Comment by adrixp** [comment] 2019-03-31 11:37
Hi @commentatorboy, 

Thanks for submitting this issue. Could you tell me which browser do you use in order to reproduce it?

Greetings!

**Comment by commentatorboy** [comment] 2019-03-31 14:47
Oh yeah sorry completly forgot it.
It is on the smartphone:
moto e5. andriod 8.0.0, chrome 73.0.3683.90
But let me tell you, it might work on your phone. So it might be hard to reproduce it.
Many did NOT encounter this issue (click the "particular problematic" link):
https://aframe.io/docs/0.9.0/components/renderer.html#precision
https://github.com/mrdoob/three.js/issues/14137

**Comment by adrixp** [comment] 2019-06-24 09:59
Hi @commentatorboy,

I have updated the examples to 0.9.2 A-frame version. Due to this is a workaround for A-frame mobile and is not the object of this library I am going to close it. Anyway it is good to know if someone use this library on mobile.

Thanks for your issue.

**Closed by adrixp** 2019-06-24 09:59 UTC
